include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true

    # Make constructors the first thing in every class
    sort_constructors_first: true

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true

    sort_pub_dependencies: false

    avoid_classes_with_only_static_members: false
