name: gmaps_autocomplete_web
description: Web platform implementation of gmaps_autocomplete
repository: https://github.com/stefan01/gmaps_autocomplete
issue_tracker: https://github.com/stefan01/gmaps_autocomplete/issues
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: GMapsAutocompleteWeb
        fileName: gmaps_autocomplete_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0

  gmaps_autocomplete_platform_interface:
    git:
      url: https://github.com/stefan01/gmaps_autocomplete
      path: gmaps_autocomplete_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0